---

#TODO: add task to install rubygems, ruby-devel, git
- block:
    - name: Set --no-user-install in gemrc
      copy:
        content: |
          gem: --no-user-install --no-document

        dest: "/etc/gemrc"
        owner: root

    - name: Gather list of installed gems
      shell: "gem list | awk '{ print $1 }'"
      register: gemlist
      changed_when: gemlist.rc != 0
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Set list of gems to install
      set_fact:
        _gems: "{{ gems|difference(gemlist.stdout) }}"

    - name: Install ruby gems
      shell: "gem install {{ item }}"
      with_items:
        - "{{ _gems }}"
      when: _gems | length > 0

  vars:
    gems:
      - activesupport
      - awesome_print
      - bcrypt_pbkdf
      - childprocess
      - clipboard
      - colorize
      - coltrane
      - ed25519
      - eventmachine
      - ffi
      - fractional
      - geo_coord
      - highline
      - i3ipc
      - i18n
      - kramdown
      - logging
      - minitest
      - mocha
      - multi_json
      - neovim
      - net-ssh
      - parallel
      - pastel
      - pry
      - pry-doc
      - rake
      - rdoc
      - rexml
      - rouge
      - ruport
      - sync
      - sys-proctable
      - treetop
      - tty-box
      - tty-command
      - tty-prompt
      - tty-screen
      - yaml
