---

- name: check if tony is already installed
  stat:
    path: /usr/local/bin/tony
  register: result
  ignore_errors: "{{ ansible_check_mode }}"

- block:
    - name: fetch tony
      get_url:
        url: "{{ tony.url }}/Tony-2.1.1-x86_64.AppImage"
        dest: "/tmp"
        validate_certs: no

    - name: link tony to bin
      shell: |
        chmod +x Tony-2.1.1-x86_64.AppImage
        mv Tony-2.1.1-x86_64.AppImage /usr/local/bin/tony
      args:
        chdir: "/tmp"

  when: not result.stat.exists
