#!/usr/bin/env zsh

mkv2mp4() {
  timestamp=$(date +%s)

  infile=$1
  outfile="${infile%.*}.mp4"

  ffmpeg -i "$infile" -c:v libx264 -preset medium -c:a vorbis -b:a 192k "$timestamp-$outfile"

  if [ $? = 0 ]; then
    rm -rf $infile
  fi
}
