---

- block:
    - name: Enable and start firewalld
      systemd:
        name: firewalld
        state: started
        enabled: yes

    - name: Permit traffic to common services
      firewalld:
        service: "{{ item }}"
        state: enabled
        permanent: yes
      with_items:
        - ntp
        - rsyncd
        - ssh
      notify: reload firewalld
      tags: ['nfs', 'ntp', 'rsyncd', 'ssh']

    - name: Permit traffic to jacktrip, barrier and qmidinet
      firewalld:
        port: "{{ item }}"
        state: enabled
        permanent: yes
      with_items:
          - 4464/udp
          - 4560/udp
          - 6666/tcp
          - 7905/tcp
          - 7906/tcp
          - 8000/udp
          - 12101/udp
          - 24800/tcp
          - 21928/udp
          - 21929/udp
          - 50924/udp
          - 55311/udp

      notify: reload firewalld

  ignore_errors: "{{ ansible_check_mode }}"
