---

- name: Ensure these directories exist
  file:
    path: "{{ item[0] }}/{{ item[1] }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0755'
    recurse: False
  with_nested:
    - [ '{{ user.home }}', '/etc/skel' ]
    - ['.config/Debauchee', '.config/Kvantum', '.config/Thunar', '.config/alacritty', '.config/dunst', '.config/gtk-3.0', '.config/gtk-4.0', '.config/htop', '.config/i3', '.config/i3status-rust/themes/', '.config/kitty', '.config/nitrogen', '.config/picom', '.config/qt5ct/colors', '.config/qt6ct/colors', '.config/qutebrowser', '.config/sxhkd', '.config/tilda', '.config/zim', '.local/share/zim/templates/plugins', '.guake', '.sonic-pi/config' ]
  tags: ['home', 'skel']

- name: Syncronize templates - shell
  template:
    src: "home/{{ item[1] }}.j2"
    dest: "{{ item[0] }}/{{ item[1] }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: yes
  with_nested:
    - [ '{{ user.home }}', '/etc/skel' ]
    - [ '.aliases', '.profile', '.ualiases', '.zlogin', '.zprofile', '.zshenv', '.zshrc', '.zshrc.local' ]
  tags: ['shell', 'profile', 'alias' ]

- name: Syncronize templates - x11
  template:
    src: "home/{{ item[1] }}.j2"
    dest: "{{ item[0] }}/{{ item[1] }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: yes
  with_nested:
    - [ '{{ user.home }}', '/etc/skel' ]
    - ['.Xresources', '.xinitrc', '.xprofile', '.xserverrc' ]
  register: x_config
  tags: ['x11', 'profile']

- name: Syncronize templates - wm
  template:
    src: "home/{{ item[1] }}.j2"
    dest: "{{ item[0] }}/{{ item[1] }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: yes
  with_nested:
    - [ '{{ user.home }}', '/etc/skel' ]
    - [ '.config/dunst/dunstrc', '.config/i3/autostart', '.config/i3/config', '.config/i3/window_assignments', '.config/i3status-rust/config.toml', '.config/i3status-rust/themes/syncopated.toml', '.config/picom/picom.conf' ]
  register: wm_config
  tags: ['i3', 'dunst', 'picom']

- name: Syncronize templates - keybindings
  template:
    src: "home/{{ item[1] }}.j2"
    dest: "{{ item[0] }}/{{ item[1] }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: yes
  with_nested:
    - [ '{{ user.home }}', '/etc/skel' ]
    - [ '.config/i3/bindings', '.config/sxhkd/sxhkdrc' ]
  register: keybinding
  tags: ['keybindings', 'i3', 'sxhkd']

- name: Syncronize templates - terminal
  template:
    src: "home/{{ item[1] }}.j2"
    dest: "{{ item[0] }}/{{ item[1] }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: yes
  with_nested:
    - [ '{{ user.home }}', '/etc/skel' ]
    - [ '.config/alacritty/alacritty.yml', '.config/kitty/cpu.conf', '.config/kitty/current-theme.conf', '.config/kitty/kitty.conf', '.config/kitty/open-actions.conf', '.config/kitty/start.conf' ]
  tags: ['terminal', 'alacritty', 'kitty', 'tilda']

- name: Syncronize templates - gtk
  template:
    src: "home/{{ item[1] }}.j2"
    dest: "{{ item[0] }}/{{ item[1] }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: yes
  with_nested:
    - [ '{{ user.home }}', '/etc/skel' ]
    - [ '.config/gtk-3.0/bookmarks', '.config/gtk-3.0/gtk.css', '.config/gtk-3.0/settings.ini', '.config/gtk-4.0/settings.ini', '.gtkrc-2.0' ]
  tags: ['gtk']

- name: Syncronize templates - qt
  template:
    src: "home/{{ item[1] }}.j2"
    dest: "{{ item[0] }}/{{ item[1] }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: yes
  with_nested:
    - [ '{{ user.home }}', '/etc/skel' ]
    - [ '.config/Kvantum/kvantum.kvconfig', '.config/qt5ct/colors/syncopated.conf', '.config/qt5ct/qt5ct.conf', '.config/qt6ct/colors/syncopated.conf', '.config/qt6ct/qt6ct.conf' ]
  tags: ['qt']

- name: Syncronize templates - applications
  template:
    src: "home/{{ item[1] }}.j2"
    dest: "{{ item[0] }}/{{ item[1] }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: '0644'
    backup: yes
  with_nested:
    - [ '{{ user.home }}', '/etc/skel' ]
    - [ '.config/htop/htoprc', '.config/qutebrowser/autoconfig.yml', '.config/qutebrowser/config.py', '.config/qutebrowser/quickmarks', '.config/zim/accelmap', '.config/zim/notebooks.list', '.config/zim/preferences.conf', '.config/zim/quicknote.conf', '.config/zim/style.conf', '.local/share/zim/templates/plugins/quicknote.txt', '.sonic-pi/config/colour-theme.properties' ]
  tags: ['htop', 'zim', 'qutebrowser', 'sonicpi']

- name: Ensure .xinitrc is executable
  file:
    path: "{{ item }}/.xinitrc"
    mode: '0755'
  with_items:
    - '/etc/skel'
    - '{{ user.home }}'
  when: x_config.changed
  tags: ['x11', 'profile']

- name: Reset perms on /etc/skel
  file:
    path: /etc/skel
    state: directory
    owner: root
    group: root
    recurse: True
  tags: ['skel']

- name: Reload i3
  command: bash -lc "i3-msg -s /run/user/{{ user.uid }}/i3/ipc-socket.* reload"
  become_user: "{{ user.name }}"
  when:
    - wm_config.changed
    - keybinding.changed
  ignore_errors: True
  tags: ['i3', 'dunst', 'picom', 'keybindings', 'sxhkd']
